server:
  port: 8443                   # HTTPS port
  ssl:
    enabled: true              # Enable SSL/TLS
    key-store: classpath:keystore.p12   # Path to your certificate
    key-store-password: sarthaktakatak    # Password you set when generating keystore
    key-store-type: PKCS12
    key-alias: myalias

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/alumni_auth_db?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
