server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: alumni-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/alumni/**
        - id: event-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/events/**
        - id: communication-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/messages/**,/api/mentorship/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
